### PR TITLE
ICS2-1411 added wsdls for each environment and updated ccn urls to ap…

### PR DESCRIPTION
**Pull request by Chrissystk**
…i platform

### CODE REVIEW

**Review by ChrisHillCap — CHANGES_REQUESTED** [review]
Although not you, as you need to touch the repo anyway I was hoping you could amend.
In the AssetsControllerISpec, the `wsdlOperationsForFileNames` is slightly incorrect.

**We only use CCN2 urls so:**
- "BusinessActivityService/ICS/RiskAnalysisOrchestrationBAS/V1/CCN2.Service.Customs.Default.ICS.RiskAnalysisOrchestrationBAS_1.0.0_1.0.0.wsdl" **can be removed**
- BusinessActivityService/ICS/AEONotificationBAS/V1/CCN2.Service.Customs.Default.ICS.AEONotificationBAS_1.0.0_CCN2_1.0.0.wsdl
BusinessActivityService/ICS/ENSLifecycleManagementBAS/V1/CCN2.Service.Customs.Default.ICS.ENSLifecycleManagementBAS_1.0.0_CCN2_1.0.0.wsdl **need to be added to it, with the appropriate filenames**

**Comment by Chrissystk** [comment]
So is this removing the files or just he tests for the files? "BusinessActivityService/ICS/RiskAnalysisOrchestrationBAS/V1/CCN2.Service.Customs.Default.ICS.RiskAnalysisOrchestrationBAS_1.0.0_1.0.0.wsdl" is imported into other schemas within the RiskAnalysisOrchestrationBAS/V1 directory.

**Comment by ChrisHillCap** [comment]
> So is this removing the files or just he tests for the files? "BusinessActivityService/ICS/RiskAnalysisOrchestrationBAS/V1/CCN2.Service.Customs.Default.ICS.RiskAnalysisOrchestrationBAS_1.0.0_1.0.0.wsdl" is imported into other schemas within the RiskAnalysisOrchestrationBAS/V1 directory.

i think the purpose of this assertion initially was to check the "top level" files only, i think if we are going to check this file we should be checking the other non ccn2 files aswell

**Comment by Chrissystk** [comment]
That's fine I just needed to know the files themselves didn't need removing.

**Comment by Chrissystk** [comment]
done

**Review by frobian21 — APPROVED** [review]

**Pull request merged**
